In [18]:
import pandas as pd
import json

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

json_file = open(r'data/15946.json')
variables = json.load(json_file)
json_file.close()

df = pd.DataFrame(variables)
df
# df = pd.read_json(r'data/15946.json')
# df

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,duration,tactics,related_events,player,position,location,pass,carry,ball_receipt,counterpress,under_pressure,ball_recovery,shot,goalkeeper,duel,dribble,foul_committed,interception,block,foul_won,bad_behaviour,substitution
0,ce508a95-38d3-4248-a50e-dc8d7e23230c,1,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.000000,"{'formation': 442, 'lineup': [{'player': {'id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39abd1c2-2575-41be-ae79-3e936eead529,2,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 206, 'name': 'Deportivo Alavés'}",0.000000,"{'formation': 4141, 'lineup': [{'player': {'id...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1148e967-380f-421f-97f0-d0c820c72984,3,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 206, 'name': 'Deportivo Alavés'}",0.000000,NaN,[7cf6876d-7c50-4d64-b999-e2a039641c81],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7cf6876d-7c50-4d64-b999-e2a039641c81,4,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.000000,NaN,[1148e967-380f-421f-97f0-d0c820c72984],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,34208ade-2af4-45c3-970e-655937cad938,5,1,00:00:00.098,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 206, 'name': 'Deportivo Alavés'}","{'id': 9, 'name': 'From Kick Off'}","{'id': 206, 'name': 'Deportivo Alavés'}",1.909000,NaN,[61da36dc-d862-416c-8ee3-1a0cd24dc086],"{'id': 6581, 'name': 'Jonathan Rodríguez Menén...","{'id': 16, 'name': 'Left Midfield'}","[61.0, 41.0]","{'recipient': {'id': 6855, 'name': 'Guillermo ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3997,be8a2725-6a34-45d5-8a49-5c9e0208e805,3998,2,00:46:41.244,91,41,"{'id': 17, 'name': 'Pressure'}",144,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 206, 'name': 'Deportivo Alavés'}",0.525000,NaN,[c68d6ade-3ad8-410d-bbdf-c8199565bf48],"{'id': 6855, 'name': 'Guillermo Alfonso Maripá...","{'id': 5, 'name': 'Left Center Back'}","[13.0, 41.0]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3998,55d71847-9511-4417-aea9-6f415e279011,3999,2,00:46:42.770,91,42,"{'id': 16, 'name': 'Shot'}",144,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.497348,NaN,[f93a1612-e2de-4efe-b202-6c4a178eebad],"{'id': 5503, 'name': 'Lionel Andrés Messi Cucc...","{'id': 17, 'name': 'Right Wing'}","[112.0, 34.6]",NaN,NaN,NaN,NaN,NaN,NaN,"{'statsbomb_xg': 0.28948128, 'end_location': [...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3999,f93a1612-e2de-4efe-b202-6c4a178eebad,4000,2,00:46:43.268,91,43,"{'id': 23, 'name': 'Goal Keeper'}",144,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 206, 'name': 'Deportivo Alavés'}",0.000000,NaN,[55d71847-9511-4417-aea9-6f415e279011],"{'id': 6629, 'name': 'Fernando Pacheco Flores'}","{'id': 1, 'name': 'Goalkeeper'}","[3.0, 43.3]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'technique': {'id': 45, 'name': 'Diving'}, 'p...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4000,e1cc4d5e-ba55-4b6b-88cc-dae13311c1d9,4001,2,00:47:32.053,92,32,"{'id': 34, 'name': 'Half End'}",144,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.000000,NaN,[cd767526-5f64-4600-acbf-e0a2608f0d00],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4001,cd767526-5f64-4600-acbf-e0a2608f0d00,4002,2,00:47:32.053,92,32,"{'id': 34, 'name': 'Half End'}",144,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 206, 'name': 'Deportivo Alavés'}",0.000000,NaN,[e1cc4d5e-ba55-4b6b-88cc-dae13311c1d9],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN